### ISSUE TITLE
Cant run it.

### ISSUE THREAD

**Issue by synchronicalIy** [luau-load/RobloxFpsUncapper#1]
When I execute the file, it says that some DLLs are missing

**Comment by luau-load** [comment]
Hello, your missing visual studio c++ runtimes, this could be downloaded at: 
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by synchronicalIy** [comment]
Hey, even after I downloaded the Visual Studio C++ Runtimes, there's some DLLs missing.
VCRUNTIME140D.dll
VCRUNTIME140_1D.dll
MSVCP140D.dll
ucrtbased.dll
